---
builds:
  - binary: battleaxe
    main: cmd/battleaxe/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
  - binary: wowaxe
    main: cmd/wowaxe/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
  - binary: daxe
    main: cmd/daxe/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
  - binary: scaxe
    main: cmd/scaxe/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    386: 32bit
    darwin: macOS
    linux: Linux
    windows: Windows
  files:
    - README.md
    - LICENSE.md
