---
builds:
  - binary: battleaxe
    main: cmd/battleaxe/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
  replacements:
    amd64: 64bit
    darwin: macOS
    linux: Linux
    windows: Windows
